### ISSUE TITLE
t.literal does not actually typecast to literal types

### ISSUE THREAD

**Issue by headjoe3** [osyrisrblx/rbx-t#1]
Actual behavior:
![image](https://user-images.githubusercontent.com/4315566/50716300-41d4e980-103e-11e9-9137-8426c401bf65.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/4315566/50716276-29fd6580-103e-11e9-9d86-b111fc0b988c.png)

Possible fix (limited to whatever types are specified though; probably shouldn't be an issue if we're dealing with literals though)
![image](https://user-images.githubusercontent.com/4315566/50716306-4d281500-103e-11e9-9f43-4196e37b0168.png)

![image](https://user-images.githubusercontent.com/4315566/50716362-82346780-103e-11e9-977b-6c138c046391.png)

**Comment by osyrisrblx** [comment]
Fixed this in 0.1.0.

`t.literal` will work for primitives
`t.exactly` will work for non-primitives
